#!/bin/bash
#PBS -l select=1:ncpus=30:model=sky_ele
#PBS -l walltime=36:00:00

cd $PBS_O_WORKDIR

source /nobackup/amondal/activate_pyenv.sh

python script16_GEOS_test_load.py
python script16_GEOS_PTQ_hrly_test.py

#end of script
