#!/bin/bash
#PBS -l select=16:ncpus=16:model=rom_ait
#PBS -l walltime=120:00:00
#PBS -N qzupdate

#set environment

#####cd $PBS_O_WORKDIR

source /nobackup/amondal/activate_pyenv.sh


python script15_multicore_3month_test.py

#end of script
