#!/bin/bash
#PBS -l  select=16:ncpus=10:model=sky_ele
#PBS -l  walltime=72:00:00


#set environment
cd $PBS_O_WORKDIR

source /nobackup/amondal/activate_pyenv.sh

 python script15_multicore_3month_test.py


#end of script
